### ISSUE TITLE
클러스터 공동 관리 데이터베이스 설계

### ISSUE THREAD

**Issue by heohyeonjin** [doheez/K8s-Big-Data-Platform#105]
클러스터 별 공동 관리 기능을 추가하였습니다.
따라서 친구 추가 데이터베이스 설계가 필요합니다.

**Comment by heohyeonjin** [comment]
JoinUserListDto 오타 수정하구
JoinUserService(ClusterMember 추가하는 서비스)에 @Transactional 어노테이션 추가하니까 해결됐당...

그리고 하나의 cluster에 동일한 user중복 제거 해야 할 것 같은데 이쪽에서 처리할깡...?

**Comment by HyeW** [comment]
중복 user 체크는 어디서 하는게 맞지?
내 생각엔 프론트에서 처리하는게 깔끔할 거 같긴한데 도히가 지금 할게 많아 보여서..

도히는 어떻게 생각해?
@doheez

**Comment by doheez** [comment]
오홍 프론트에서 처리해볼게!

**Comment by heohyeonjin** [comment]
호오.. 근데 추가하면 중복 유저 정보도 계속 ClusterMember 데이터베이스에 저장되는뎅 상관 없겠지 ..? 백앤드에서 처리하는게 맞으려나?.?

**Comment by doheez** [comment]
프론트에서 백으로 중복된 유저 자체를 넘기지 않으면 되는 거 아니야? 사용자가 이메일을 여러 개 입력하거나 일부를 X 버튼으로 삭제하는 그 과정까진 프론트에서만 이메일 리스트를 가지고 있고, 확인 버튼을 클릭해야 그 이메일 리스트가 API 요청을 통해 백으로 넘어가!

추가하면 중복 유저 정보도 계속 ClusterMember 데이터베이스에 저장된다는 게 무슨 말인지 잘 모르겠다...

**Comment by heohyeonjin** [comment]
오 ㅎㅎ 맞네 계속 postman으로 테스트 해서 헷갈렸다 ..
ClusterMember가 cluster 공동 관리 내역 저장하는 데이터베이스인데 애초에 중복 유저 안넘기면 중복 저장 안될듯!

수고해죠 언니야..
