### ISSUE TITLE
Hadoop/Spark slave 생성 문제

### ISSUE THREAD

**Issue by heohyeonjin** [doheez/K8s-Big-Data-Platform#32]
hadoop/spark 모두 operator는 [client-java](https://github.com/kubernetes-client/java) 라이브러리를 이용하여 생성 완료한 상태이다. 
- Deployment 생성 완료
- RoleBinding 생성 완료
- ServiceAccount 생성 완료

앞서 생성한 operator를 이용하여 worker및 slave 개수를 지정해서 pod를 생성하는 단계에서, 
기존에 참고하던 외부 라이브러리([alicek106/k8s-hadoop-operator](https://github.com/alicek106/k8s-hadoop-operator), [radanalyticsio/spark-operator](https://github.com/radanalyticsio/spark-operator))의 쿠버네티스 오브젝트에 해당하는 자바 객체가 clinet-java 라이브러리에 없었다. 

자세히 설명하자면 client-java 라이브러리에 존재하는 쿠버네티스 오브젝트(deployment, rolebinding, serviceAccount)와  API호출을 위한 함수를 통해 operator 생성 및 실행이 가능하였지만, 참고하던 라이브러리(alicek106/k8s-hadoop)의 slave 생성 YAML 파일에 지정된  HadoopService라는 오브젝트는 해당 라이브러리 내에서 자체 제작한 쿠버네티스 오브젝트로, 이 오브젝트를 client-java를 통해 생성할 수 없었다. 

<br>

🔢 결론 

Operator의 동작 원리에 대해 자세히 공부한 후, Client-java를 활용하여 연결할 수 있는 YAML파일 형식을 직접 제작하는 방법을 모색 중이기는 하나 혹시나 더 좋은 방법이 있다면 피드백 부탁드립니다..

**Comment by idoburnish** [comment]
1. 먼저 cmd 창에서 kubectl 명령어를 통해 Custom Resource Definition(CRD) YAML 파일 이용해서 Custon Resource 정의하고, 등록한다.
2. 그 후, 아래와 같이 API 호출한다.
```java
CustomObjectsApi apiInstance = new CustomObjectsApi(ClientBuilder.standard().build());
String group = "alicek106.hadoop";
String version = "v1alpha1";
String namespace = "hadoop";
String plural = "hadoopservices";
Object body = new Example();

try {
    System.out.println(apiInstance.getApiClient());
    Object result = apiInstance.createNamespacedCustomObject(group, version, namespace, plural, body, null, null, null);
    System.out.println(result);
} catch (ApiException e) {
    System.err.println("Exception when calling CustomObjectsApi#patchNamespacedCustomObject");
    System.err.println("Status code: " + e.getCode());
    System.err.println("Reason: " + e.getResponseBody());
    System.err.println("Response headers: " + e.getResponseHeaders());
    e.printStackTrace();
}
```
