### ISSUE TITLE
클러스터 관리 버튼 클릭 시 다이얼로그 구현

### ISSUE THREAD

**Issue by doheez** [doheez/K8s-Big-Data-Platform#35]
## Description
My Page에서 Hadoop/Spark 클러스터 관리 기능을 제공하려면 각 클러스터 컴포넌트에서 Add/Delete Cluster 버튼 클릭 시 사용자의 요청을 입력받아야 한다.

![image](https://user-images.githubusercontent.com/57346425/168463161-4dc3d970-51c6-41d5-b505-36c7857f05c7.png)

이를 위해 `Add Cluster 다이얼로그`와 `Delete Cluster 다이얼로그`를 각각 생성하고 세부 사항을 정의한다.
- Add Cluster 다이얼로그
    - 추가할 클러스터 개수를 입력받는 TextField 구현
- Delete Cluster 다이얼로그
    - 클러스터 삭제 시 복구할 수 없다는 경고 메세지를 Alert로 구현

**Comment by doheez** [comment]
## Situation
My Page에서 Hadoop이나 Spark 클러스터 관리 버튼(Add/Delete Cluster)을 클릭하면 다음 두 가지 다이얼로그가 상황에 맞게 보여진다.

### Add Cluster Dialog
추가할 클러스터의 개수를 입력받는다. 현재는 어떤 버튼을 클릭하더라도 다이얼로그가 닫히도록 동작하며, 백엔드 API 구현 후엔 OK 버튼 클릭 시 백엔드로 클러스터 개수를 넘겨줄 예정이다.

![image](https://user-images.githubusercontent.com/57346425/168463281-8fc18157-d986-417c-ac78-c7a0e3121e48.png)

### Delete Cluster Dialog
클러스터 복구 불가 경고 메세지를 출력한다. 마찬가지로 지금은 버튼 클릭 시 다이얼로그가 닫히며, 이 UI에 맞게 API를 구현한다면 삭제할 클러스터를 지정하지 않기 때문에 모든 클러스터를 삭제하도록 동작할 것이다.

![image](https://user-images.githubusercontent.com/57346425/168463289-a45d525b-f969-41c1-9932-bea678aad631.png)

## Question
1. 삭제할 클러스터를 따로 지정하지 않고 지금처럼 전체 클러스터를 삭제하는 게 맞아?
2. 아니면 삭제할 클러스터도 개수를 입력받거나(1) 테이블에서 삭제할 클러스터를 선택하도록(2) UI를 변경해야 할까?
3. 2-2처럼 바꾼다면 쿠버네티스에서 직접 선택한 클러스터를 삭제하는 게 가능해?

코멘트로 답변 부탁해~~ @HyeW @idoburnish @heohyeonjin

**Comment by idoburnish** [comment]
`add/delete`보다는 `increase/decrease` 같은 단어가 뭔가 slave node 수를 늘이고 줄인다는 명확한 뜻을 담을 것 같긴 해 !
그리고 아예 `delete cluster`라는 클러스터 전체를 삭제할 수 있는 그런 버튼으로 만드는 것도 좋을 것 같아.

**Comment by doheez** [comment]
그럼 `Increase Node`, `Decrease Node`, `Delete Cluster` 세 가지 버튼이 필요한 건가? 내가 지금까지 클러스터의 의미를 잘못 이해하고 있었던 것 같은데 예를 '5개'를 생성할 때 저 자체는 하나의 클러스터이고 5개 각각은 노드랑 매칭되는 개념이야?

**Comment by idoburnish** [comment]
웅웅 처음에 Hadoop 클러스터 생성 버튼 눌러서 크기를 5로 지정하면, Hadoop 클러스터 1개가 생성되고 그 안에 master node 1개 slave node 5개 이렇게 생성되도록 구현되어 있어 !

**Comment by doheez** [comment]
앗 그런 거구나 그럼 UI에 박아놓은 텍스트 중에 `Number of Clusters` 이런 건 `Number of Nodes`로 바꾸는 게 맞겠네...!

그럼 `Increase/Decrease Node` 다이얼로그에서는 각각 증가시키거나 감소시킬 노드 개수를 입력 받으면 되는 거야? 그리고 노드 감소시킬 때 입력한 개수만큼 노드를 랜덤하게 감소시키는 건지 직접 감소시킬 노드를 선택해야 하는 건지 알려줘!

**Comment by doheez** [comment]
## 대면 회의 결과
Cluster Management 섹션에 버튼 3개를 생성하고 각 버튼에 맞는 다이얼로그를 구현한다.
1. `Increase Node`: 클릭 시 다이얼로그에서 증가시킬 Hadoop/Spark 노드 개수를 입력받는다.
2. `Decrease Node`: 클릭 시 다이얼로그에서 감소시킬 Hadoop/Spark 노드 개수를 입력받는다.
3. `Delete Cluster`: 클릭 시 다이얼로그에서 Hadoop/Spark 클러스터를 삭제하면 복구할 수 없다는 경고 문구를 출력한다.

다이얼로그에서 확인/취소 버튼 시 동작은 백엔드에서 관련 API 구현을 완료하면 해당 API로 사용자 입력 처리를 요청할 예정이다.
