### ISSUE TITLE
Hadoop 클러스터 크기 조절

### ISSUE THREAD

**Issue by idoburnish** [doheez/K8s-Big-Data-Platform#40]
사용자로부터 Hadoop 클러스터 내의 slave node 개수 조절 요청을 받으면, 그에 대한 응답을 해야 합니다.
Custum Resource를 이용해 cluster size의 개수를 조절하는 기능을 구현하고자 합니다.

**Comment by idoburnish** [comment]
클러스터 크기 조절 시, already exist라는 에러가 뜨면서 크기 조절이 되지 않는다. 

![image](https://user-images.githubusercontent.com/69456626/169750897-7c483aa4-9cab-43f6-a5f6-ec36c59b66f1.png)

이거 어떤 방식으로 해야 할 것 같아 .. ? 아이디어 있어 ??

@heohyeonjin

**Comment by idoburnish** [comment]
```java
apiVersion: alicek106.hadoop/v1alpha1
kind: HadoopService
metadata:
  name: example-hadoopservice
spec:
  # Add fields here
  clusterSize: 3
```

HadoopService를 CRD를 통해 정의하였고, 위의 형식대로 slave 개수가 3인 HadoopService(Hadoop Cluster)를 생성하였습니다.  
그 후, 코드 상에서 클러스터 크기를 조절하기 위해 변경된 clusterSize로 body를 생성하여 `replaceNamespacedCustomObject` API를 호출하면 성공적으로 200 OK 응답이 오고, return 값으로 오는 객체 안의 clusterSize도 변경된 값으로 전달되어 옵니다. 하지만, 실제로 쿠버네티스 안의 pod(slave) 개수가 조절되지는 않습니다. 이것은 operator 동작의 문제인가요 ? 아니면 CRD를 다시 정의해야되는 건가요 ?

혹시 이거 멘토님께 여쭤봐 줄 수 있어 ??
@HyeW

**Comment by HyeW** [comment]
응응 메일 보냈어
